-- AlterTable: Add new fields to Listing
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "askingPrice" DOUBLE PRECISION;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "performanceStatus" TEXT;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "noteType" TEXT;

-- AlterTable: Add new fields to Asset
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "propertyType" TEXT;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "county" TEXT;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "yearBuilt" INTEGER;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "floorSizeSqFt" DOUBLE PRECISION;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "lotSizeSqFt" DOUBLE PRECISION;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "bedrooms" INTEGER;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "bathrooms" DOUBLE PRECISION;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "lastPaymentReceivedDate" TIMESTAMP(3);
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "paymentAccepted" TEXT;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "isInterestOnly" BOOLEAN;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "interestOnlyPeriod" INTEGER;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "totalMonthlyPayment" DOUBLE PRECISION;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "legalStatus" TEXT;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "isJudicialState" BOOLEAN;
